/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author mzenm
 */
public class frameUtama extends javax.swing.JFrame {

    /**
     * Creates new form frameUtama
     */
    public frameUtama() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFormGuru = new javax.swing.JButton();
        btnFormSiswa = new javax.swing.JButton();
        btnFormKelas = new javax.swing.JButton();
        btnFormJadwal = new javax.swing.JButton();
        btnFormPelajaran = new javax.swing.JButton();
        btnFormNilai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));

        btnFormGuru.setText("Form Guru");
        btnFormGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormGuruActionPerformed(evt);
            }
        });

        btnFormSiswa.setText("Form Siswa");
        btnFormSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormSiswaActionPerformed(evt);
            }
        });

        btnFormKelas.setText("Form Kelas");
        btnFormKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormKelasActionPerformed(evt);
            }
        });

        btnFormJadwal.setText("Form Jadwal ");
        btnFormJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormJadwalActionPerformed(evt);
            }
        });

        btnFormPelajaran.setText("Form Pelajaran");
        btnFormPelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormPelajaranActionPerformed(evt);
            }
        });

        btnFormNilai.setText("Form Nilai");
        btnFormNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormNilaiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("MAIN MENU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnFormNilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormPelajaran, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(btnFormJadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFormGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(btnFormGuru)
                .addGap(18, 18, 18)
                .addComponent(btnFormSiswa)
                .addGap(18, 18, 18)
                .addComponent(btnFormKelas)
                .addGap(18, 18, 18)
                .addComponent(btnFormJadwal)
                .addGap(18, 18, 18)
                .addComponent(btnFormPelajaran)
                .addGap(18, 18, 18)
                .addComponent(btnFormNilai)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormGuruActionPerformed

        new frameGuru().setVisible(true);
    }//GEN-LAST:event_btnFormGuruActionPerformed

    private void btnFormSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormSiswaActionPerformed
        new frameSiswa().setVisible(true);       
    }//GEN-LAST:event_btnFormSiswaActionPerformed

    private void btnFormKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormKelasActionPerformed
        new frameKelas().setVisible(true);
    }//GEN-LAST:event_btnFormKelasActionPerformed

    private void btnFormJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormJadwalActionPerformed
        new frameJadwal().setVisible(true);
    }//GEN-LAST:event_btnFormJadwalActionPerformed

    private void btnFormPelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormPelajaranActionPerformed
        new framePelajaran().setVisible(true);
    }//GEN-LAST:event_btnFormPelajaranActionPerformed

    private void btnFormNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormNilaiActionPerformed
        new frameNilai().setVisible(true);
    }//GEN-LAST:event_btnFormNilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormGuru;
    private javax.swing.JButton btnFormJadwal;
    private javax.swing.JButton btnFormKelas;
    private javax.swing.JButton btnFormNilai;
    private javax.swing.JButton btnFormPelajaran;
    private javax.swing.JButton btnFormSiswa;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
